CREATE DATABASE T_MODA
USE T_MODA

CREATE TABLE  Marca
(
	IdMarca		INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(100) NOT NULL UNIQUE
);
INSERT INTO Marca(Nome) VALUES	('Nike'),('Vans'),('Adidas')

CREATE TABLE COR
(
	IdCor	INT PRIMARY KEY IDENTITY
	,Nome	VARCHAR(100) NOT NULL UNIQUE
)
INSERT INTO COR(Nome)	VALUES	('BRANCA'),('VERMELHA'),('AZUL'),('ROXO'),('VERDE')

CREATE TABLE TAMANHO
(
	IdTamanho	INT PRIMARY KEY IDENTITY
	,Tamanho	VARCHAR(10) NOT NULL UNIQUE
);

INSERT INTO TAMANHO(Tamanho) VALUES	('P'),('M'),('G'),('GG')
	
CREATE TABLE CAMISETA
(
	IdCamiseta	INT PRIMARY KEY IDENTITY
	,Tipo		VARCHAR(100) NOT NULL 
	,IdMarca	INT FOREIGN KEY REFERENCES	Marca(IdMarca)
	,IdTamanho	INT FOREIGN KEY REFERENCES	TAMANHO(IdTamanho)
	,IdCor		INT FOREIGN KEY REFERENCES COR (IdCor)
);
INSERT INTO CAMISETA (Tipo ,IdMarca ,IdTamanho ,IdCor) VALUES	('CAMISA', 1, 1, 1)
															,('CASACO', 2 ,2 ,2)
															,('CAMISA',3,3,3)
															,('CASACO',1,4,4)
															,('CAMISA',3,1,5);

DROP TABLE CAMISETA;

SELECT * FROM Marca

SELECT * FROM COR

SELECT * FROM TAMANHO

SELECT * FROM CAMISETA

SELECT CAMISETA.Tipo ,Marca.Nome AS Marca ,TAMANHO.Tamanho ,COR.Nome AS Cor
	FROM CAMISETA
	FULL JOIN Marca
	ON Marca.IdMarca = CAMISETA.IdMarca
	FULL JOIN TAMANHO
	ON CAMISETA.IdTAmanho = TAMANHO.IdTamanho
	FULL JOIN COR
	ON COR.IdCor = CAMISETA.IdCor
	
